name: nrlifecare
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  device_preview: ^0.5.5
  easy_localization: ^2.3.3
  flutter_screenutil: ^4.0.3
  flutter_svg: ^0.19.0
  get: ^3.24.0
  pin_code_fields: ^6.1.0

dev_dependencies:
  lint: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/images/facebook_logo.svg
    - assets/images/google_logo.svg

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
