name: nrlifecare
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  cloud_firestore: ^0.16.0+1
  firebase_auth: ^0.20.0+1
  firebase_core: 0.7.0

  # Inbuilt
  cupertino_icons: ^1.0.0

  # Localization
  easy_localization: ^2.3.3

  # Floating Button
  fab_circular_menu: ^1.0.1

  # Responsive
  flutter_screenutil: ^4.0.3

  # Slide to Delete
  flutter_slidable: ^0.5.7

  # Loading Indicator
  flutter_spinkit: ^4.1.2+1
  shimmer: ^1.1.2

  # List animation
  flutter_staggered_animations: ^0.1.2

  # Image Asset
  flutter_svg: ^0.19.0
  cached_network_image: ^2.5.0

  # State management
  get: ^3.24.0

  # Authentication
  google_sign_in: ^4.5.9

  # Search Bar
  material_floating_search_bar: ^0.2.6

  # Local storage
  shared_preferences: ^0.5.12+4

  # Razorpay
  razorpay_flutter: 1.1.0

dev_dependencies:
  build_runner: any
  json_serializable: ^3.5.1
  lint: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    # Translation
    - assets/translations/

    # FB, Google Logo
    - assets/images/facebook_logo.svg
    - assets/images/google_logo.svg

    # Icons
    - assets/icons/search_icon.svg
    - assets/icons/shopping-basket.svg
    - assets/icons/swipe-left.svg

    # logo
    - assets/images/logo.jpeg

    # About us Images
    - assets/images/aboutus_1.png
    - assets/images/aboutus_2.png
    - assets/images/aboutus_3.png
    - assets/images/aboutus_4.png

    # Contact us Images
    - assets/images/contactus_1.png
    - assets/images/contactus_2.png
    - assets/images/contactus_3.png
    - assets/images/contactus_bottom_1.png
    - assets/images/contactus_bottom_2.png
    - assets/images/contactus_bottom_3.png
    - assets/images/contactus_bottom_4.png
    - assets/images/contactus_bottom_5.png
    - assets/images/contactus_bottom_6.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
