name: nrlifecare
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^2.5.0
  cloud_firestore: ^0.16.0+1
  cupertino_icons: ^1.0.0
  easy_localization: ^2.3.3
  fab_circular_menu: ^1.0.1
  firebase_auth: ^0.20.0+1
  firebase_core: 0.7.0
  flutter_screenutil: ^4.0.3
  flutter_slidable: ^0.5.7
  flutter_spinkit: ^4.1.2+1
  flutter_staggered_animations: ^0.1.2
  flutter_svg: ^0.19.0
  get: ^3.24.0
  google_sign_in: ^4.5.9
  material_floating_search_bar: ^0.2.6
  razorpay_flutter: 1.1.0
  shared_preferences: ^0.5.12+4
  shimmer: ^1.1.2
  telephony: ^0.0.8
  geolocator: ^6.2.1
  introduction_screen: ^1.0.9

dev_dependencies:
  build_runner: any
  json_serializable: ^3.5.1
  lint: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    # Translation
    - assets/translations/

    #  Onboarding Images
    - assets/images/ob_cart.svg
    - assets/images/ob_delivery.svg
    - assets/images/ob_medicine.svg
    - assets/images/ob_payment.svg
    - assets/images/ob_search.svg

    # FB, Google Logo
    - assets/images/google_logo.svg

    # Icons
    - assets/icons/search_icon.svg
    - assets/icons/shopping-basket.svg
    - assets/icons/swipe-left.svg

    # logo
    - assets/images/logo.jpeg

    # About us Images
    - assets/images/aboutus_1.png
    - assets/images/aboutus_2.png
    - assets/images/aboutus_3.png
    - assets/images/aboutus_4.png

    # Contact us Images
    - assets/images/contactus_1.png
    - assets/images/contactus_2.png
    - assets/images/contactus_3.png
    - assets/images/contactus_bottom_1.png
    - assets/images/contactus_bottom_2.png
    - assets/images/contactus_bottom_3.png
    - assets/images/contactus_bottom_4.png
    - assets/images/contactus_bottom_5.png
    - assets/images/contactus_bottom_6.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/font/Roboto-Regular.ttf
